### ISSUE TITLE
AsyncAction<> problem

### ISSUE THREAD

**Issue by wrbl606** [leocavalcante/ReduRx#3]
I was trying to create a AsyncAction for my LoginPageModel state class. 
The problem is, that the required _reduce(state)_ method tries to return Future<Computation<LoginPageModel>> instead of Future<LoginPageModel>.

If i try to manually "fix" conflicting types, this message shows up:
> error: 'DoLogin.reduce' ('(LoginPageModel) → Future<LoginPageModel>') isn't a valid override of 'AsyncAction.reduce' ('(LoginPageModel) → Future<(LoginPageModel) → LoginPageModel>'). (invalid_override at [res_fleet_management_client] lib/actions/loginPageActions.dart:33)

Here's how it looks:
![obraz](https://user-images.githubusercontent.com/15102395/50217042-d5908f80-0387-11e9-974c-92134779f19b.png)

In your tutorial, AsyncAction's reduce method looks like this:
![obraz](https://user-images.githubusercontent.com/15102395/50217102-0ffa2c80-0388-11e9-8bb0-a4a0b395c0c8.png)

Am I missing something? What can be the issue?

**Comment by wrbl606** [comment]
I just checked: the issue is gone when I switch back from 1.0.0+1 version to 0.2.3+3 one.

**Comment by leocavalcante** [comment]
Hi @wrbl606 
Sorry about that. The tutorial was made on a previous version of the library.
Now `AsyncAction`s should return computations, this prevents race conditions.

A `Computation` is a type interface for `State -> State`. You can update you code to:

```dart
class DoLogin extends AsyncAction<LoginPageModel> {
  @override
  Future<Computation<LoginPageModel>> reduce(LoginPageModel state) async {
    return (LoginPageModel state) => LoginPageModel(
      login: state.login,
      password: state.password,
      isLoading: false,
      errorMessage: 'Error',
    );
  }
}
```
